version: '3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    container_name: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: kaddem
      MYSQL_USERNAME: root

    ports:
      - 3306:3306


  spring-back:
    image: hejer77/kaddem:latest
    container_name: kaddem
    ports:
      - 8089:8089
    depends_on:
      - mysql
