
version: "3.8"
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "0000"
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

  KaddemApplication:
    depends_on:
      - mysqldb
    image: eyagoutet/5bi6-g3-kaddem-1.0:latest
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: "0000"
    ports:
      - 8089:8089
    stdin_open: true
    tty: true
  prometheus:
      image: prom/prometheus:v2.44.0
      container_name: prometheus
      ports:
        - "9090:9090"
      volumes:
        - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
        image: grafana/grafana:9.5.2
        container_name: grafana
        ports:
          - "3000:3000"
        restart: unless-stopped
        volumes:
          - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
volumes:
  db:
